[package]
name = "vst3-host"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
either = "1.12.0"
encoding_rs = "0.8.34"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = { version = "3" }
vst3 = "0.1"

